### ISSUE TITLE
Parsing materials

### ISSUE THREAD

**Issue by RPDJF** [IlYAN-FISHERMAN/miniRT-42#31]
Parsing various materials is necessary for creating objects with mirror, plastic, or metal finishes.

Suggestion:
- Introduce predefined materials as follows:
```rt
sp   0,0,0    2    255,255,255    metal
```
This line parses a predefined metal material.
Recommended materials include: `metal`, `glass`, `plastic`, and `mirror`.

Added value:
Implementing this suggestion could allow for material definitions within .rt files, such as:
```rt
define new_mat `diffuse 0.0 - 1.0`, `specular 0.0 - 1.0`, `shininess 0 - 1000`, `reflectivity 0.0 - 1.0`, `transparency 0.0 - 1.0`, `refract index 1.0 - 2.5`

sp 0,0,0 2 255,255,255 new_mat
```

Note: In the absence of a defined material, a default should be used.

**Comment by RPDJF** [comment]
@IlYAN-FISHERMAN since we need to support bump map texture, how should we handle it ?
i already provide a ``t_bumpmap	*load_bumpmap(char *filename)`` function to load the file

i would suggest to add an optional parameter in the defines, which will be a string containing a filename
we could even add an option to define the BUMP_SCALE: currently it is hardcoded as "0.5" and can be overwritten by using the -D flag. But it could be interesting to define it inside the material structure instead, so each object can have his own BUMP_SCALE

**Comment by IlYAN-FISHERMAN** [comment]
#44
